import { Eye, EyeOff, Fingerprint, GitBranch, Globe2, LockKeyhole, ShieldCheck, TimerReset } from 'lucide-react';

export default function ProtocolPage() {
  return <div className="page page-narrow protocol-page">
    <div className="page-heading"><div className="section-kicker">Privacy notes</div><h1>Disclose the result.<br /><em>Keep the reason.</em></h1><p>VoteVault uses a Merkle membership proof for operator-approved, salted credentials. A visitor proves they hold one approved leaf and that their private signal clears the room rule. The public chain sees the checks and the result—not the path’s story.</p></div>
    <div className="privacy-columns"><section className="privacy-card public"><Globe2 size={20} /><h3>Public ledger</h3><ul><li>minimum signal, room salt, expiry, and capacity</li><li>operator commitment and authorized tree root</li><li>room status and aggregate visitor count</li><li>spent receipt/nullifier entries</li><li>transaction timing and network metadata</li></ul></section><section className="privacy-card private"><LockKeyhole size={20} /><h3>Private witness</h3><ul><li>signal value and member secret</li><li>salted credential commitment preimage</li><li>Merkle authentication path and selected leaf</li><li>operator secret used for control circuits</li><li>anything not deliberately disclosed by the contract</li></ul></section></div>

    <section className="section protocol-flow"><div className="section-head"><div><div className="section-kicker">The proof boundary</div><h2>A leaf, a path,<br />a quiet answer.</h2></div><p>The operator registers a commitment. The member later reconstructs that commitment privately and supplies the matching path from the live tree.</p></div><div className="flow-rail"><article><span className="flow-number">01</span><GitBranch size={21} /><h3>Approved leaf</h3><p><code>credential_key(signal, secret, room_salt)</code> creates a salted commitment. The operator registers only that commitment.</p></article><article><span className="flow-number">02</span><Fingerprint size={21} /><h3>Merkle membership</h3><p>The witness supplies a path whose leaf equals the computed commitment. The circuit checks it against the public root.</p></article><article><span className="flow-number">03</span><ShieldCheck size={21} /><h3>Threshold + nullifier</h3><p>The private signal clears the public minimum, then a room-scoped receipt is checked unused before the count advances.</p></article></div></section>

    <section className="section observer-section"><div className="section-head"><div><div className="section-kicker">Observer model</div><h2>What the chain can say.</h2></div><p>A valid transaction is a public event. Privacy here means reducing what that event can bind to—not making the event disappear.</p></div><div className="insight-grid"><article className="insight"><ShieldCheck size={20} /><div><h3>It can verify</h3><p>The room was live, the proof matched the current root, the hidden signal cleared the threshold, and the nullifier was unused.</p></div></article><article className="insight"><EyeOff size={20} /><div><h3>It should not recover</h3><p>The signal value, member secret, selected credential leaf, Merkle path, or preimage of the room-scoped receipt.</p></div></article><article className="insight"><Eye size={20} /><div><h3>It may still infer</h3><p>Timing, transaction frequency, wallet addresses, a tiny room, or side-channel context can weaken unlinkability.</p></div></article></div></section>

    <section className="panel limits-panel"><div className="section-kicker">Limits worth keeping visible</div><h2>Privacy is a boundary, not a spell.</h2><div className="limits-grid"><div><TimerReset size={18} /><h3>Timing can correlate</h3><p>A proof submitted immediately after an invitation, or in a very small room, may be easy to associate with a person outside the circuit.</p></div><div><Fingerprint size={18} /><h3>Small sets are fragile</h3><p>Merkle membership hides which leaf was used; it cannot manufacture anonymity when only one or two people could plausibly hold an approved credential.</p></div><div><LockKeyhole size={18} /><h3>Remote provers matter</h3><p>Wallets or proving services can observe operational metadata. Review their trust model; private witnesses are not automatically private from every provider.</p></div></div></section>

    <section className="section"><div className="section-head"><div><div className="section-kicker">Compact at a glance</div><h2>The circuit asks one useful question.</h2></div></div><div className="code-block"><span className="accent">const</span> credential = credential_key(signal, secret, room_salt);<br /><span className="accent">const</span> path = find_credential_path(credential);<br /><span className="accent">assert</span>(path.leaf == credential);<br /><span className="accent">assert</span>(authorized_credentials.checkRoot(path));<br /><span className="accent">assert</span>(signal &gt;= minimum_signal);<br /><span className="accent">assert</span>(!spent_tokens.member(receipt));<br /><br /><span className="comment">// disclose only the accepted state transition</span><br />verified_visitors.increment(1);</div></section>
  </div>;
}
